### ISSUE TITLE
Combining a facet filter and an exposed filter does not work

### ISSUE THREAD

**Issue by thomascys** [AcroMedia/commerce-demo#16] opened 2018-01-29 09:45 UTC
For example:
When you click on the facet filter "Urban Living" and after that you want to sort by Title, descending. The Facet filter is lost.

**Comment by MikeAcro** [comment] 2018-01-29 16:24
You are correct. Thanks for reporting this, I'll look into it.

**Comment by thomascys** [comment] 2018-01-30 08:06
Thanks for looking into it. I'm dealing with the same problem and tried to solve it with [Core views facets](https://www.drupal.org/project/core_views_facets) but no luck.

**Comment by MikeAcro** [comment] 2018-01-30 16:37
Alrighty. Thanks for letting me know. If you do end up finding a solution, please keep me informed. I'll do the same. :+1:

**Comment by MikeAcro** [comment] 2018-02-14 18:51
Removing the 'bug' label since I believe this is working as designed... we just need to find a workaround for it. I'll call it an enhancement for now.

**Comment by MikeAcro** [comment] 2018-06-25 17:07
A coworker of mine found a very simple fix for this! In the .theme you need to replace the form action with the current URL path so that the active facets (which get added in the path) are carried through. One thing to note is that this only works if the View is not using AJAX, which the demo side does not. You can see it working in the demo site catalog.

Here's the code that does it: https://github.com/AcroMedia/commerce-demo/commit/37099de0b88b7261d06ec52961792a9cbe235349

I'm going to close this issue.

**Closed by MikeAcro** 2018-06-25 17:07 UTC
Labels: enhancement

**Comment by MikeAcro** [comment] 2018-06-27 15:15
I spoke too soon. The code snippet linked to above ends up breaking the site search because it tries to maintain facets and filters on any page, not just the catalog. [Here's an update](https://github.com/AcroMedia/commerce-demo/commit/75d64c7ee5a74ba2c7b07d22b3db433b74708080) that first makes sure you're within the product catalog before maintaining the active facets and filters in the url path.
